//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieHelperBot
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieHelperBotEntities : DbContext
    {
        public MovieHelperBotEntities()
            : base("name=MovieHelperBotEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lists> Lists { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UsersList> UsersList { get; set; }
    }
}
